# Macos Build

name: macos-build-hrdb

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: macos-10.15

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a set of commands using the runners shell
      - name: Install libs
        run: |
           brew install qt5
           brew install sdl2
           echo "/usr/local/opt/qt@5/bin" >> $GITHUB_PATH
           echo "Qt5_DIR=/usr/local/opt/qt@5/lib/cmake/Qt5" >> $GITHUB_ENV
           mkdir output
      - name: Build hatari
        run: |
          ./configure
          make -j 2
          cd src
          chmod +x hatari.app/Contents/MacOS/hatari
          ls -rl
          mv hatari.app ../output/
      - name: build hrdb
        run: |
          export
          cd tools/hrdb
          qmake .
          make
          chmod +x hrdb.app/Contents/MacOS/hrdb
      - name: package
        run: |
           cd tools/hrdb
           macdeployqt hrdb.app
           #ls -Rl *
           mv hrdb.app ../../output/
      - name: "Upload artifacts"
        uses: actions/upload-artifact@v2
        with:
          name: hrdb-${{ github.sha }}
          path: output
          
           
